### ISSUE TITLE
CM-BERT's paper link cannot be opened or downloaded normally

### ISSUE THREAD

**Issue by Columbine21** [thuiar/thuiar.github.io#1]
![image](https://user-images.githubusercontent.com/46373350/101303050-27ce6200-3878-11eb-8e03-a9e95d65bb17.png)

这个链接到的pdf 貌似是CH-SIMS的论文。

**Comment by MFYDev** [comment]
@Columbine21 好的，我马上检查修改

**Comment by MFYDev** [comment]
已将链接暂时修复为作者提供的原始链接  

https://doi.org/10.1145/3394171.3413690

但是由于ACM官网出现问题导致暂时无法下载，正在寻求替代方案

感谢！

**Comment by MFYDev** [comment]
经核实，官网已修复，issue关闭
